### ISSUE TITLE
creating my own domain name on mesh net

### ISSUE THREAD

**Issue by veso266** [interfect/cjdns-installer#10]
Hi this question is not related to cjdns-installer (which BTW works great) but I don't know where to ask it

so I would like to know how to create my own domain (something.si for instance) on the Hyperboria network? Can I even run my own DNS Server?

Thanks for Anwsering and Best Regards

**Comment by interfect** [comment]
What's commonly done is to just use the Internet DNS system, and use your
Hyperboria IPv6 address as the IP you want the name to resolve to (using an
AAAA record).

There has long been talk of a distributed DNS system for Hyperboria, but
that always raises the question of *which* distributed DNS system to use,
which we have never had answered satisfactorily.

You can run your own DNS server and make it accessible over cjdns (and for
a while someone was), but the latency ends up being pretty high if you just
set a Hyperboria IP as your DNS server in your OS, and it's going to have
much worse uptime than whatever's built into your router or provided by
your ISP.

If you try and set a meshnet IPv6 as the naneserver for your domain, I
don't think it will work, because when people do lookups through their ISP
name servers those name servers will want to call up your name server and
won't be able to.

**Comment by veso266** [comment]
Thanks I can see thet hyperboria.name is done that way to 

but there is a small problem that nobody will put AAA record to my hyperboria ip for something.si for free

is it posible to auto assihg my DNS server to someone connecting to my? (like routers do with ther DHCP Servers)?

**Comment by interfect** [comment]
The downside is that you have to pay a registrar to register the name. Or
is the problem that you already registered the name but the people you
registered the name with won't also host your AAAA record for you?

If you don't want to pay to register a name, you can try using some of the
free DNS providers. I believe http://freedns.afraid.org/ supports AAAA
records, and they have a lot of domains to choose from. You would get
something like something.qc.to or something.zanity.net, under one of the
domains that someone has contributed to their system.

If there's interest maybe we could maybe register a meshnet-y domain and
add it to their system, specifically for meshnet people.

Alternatively, I think hyperboria.name will give you subdomains if you ask.

**Comment by veso266** [comment]
Will try dot.tk 

Thats good idea to have meshnet-y domain so people would have something.meshnet-y
