### ISSUE TITLE
SimpleSC::GetServiceDescription return empty string and error code 5

### ISSUE THREAD

**Issue by kunalailani** [interfect/cjdns-installer#13]
hey admin,

any of the SimpleSC:: command not working.

**Comment by interfect** [comment]
Do you have the applicable plugin installed in your NSIS compiler?

**Comment by kunalailani** [comment]
Thanks for your reply.

Yes, I've placed SimpleSC.dll inside Plugins folder(i.e, inside C:\Users\user\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Plugins).
Actually I'm using nsis with electron-builder and i want to install a service which run in auto start mode.

**Comment by interfect** [comment]
I don't know how much support I can provide for the SimpleSC plugin. I'm
just a fellow user.

Did you contact its authors? Can you successfully use other NSIS plugins
with electron-builder?


On Aug 1, 2017 11:13 PM, "kunalailani" <notifications@github.com> wrote:

Thanks for your reply.

Yes, I've placed SimpleSC.dll inside Plugins folder(i.e, inside
C:\Users\user\AppData\Local\electron-builder\cache\nsis\
nsis-3.0.1.13\Plugins).
Actually I'm using nsis with electron-builder and i want to install a
service which run in auto start mode.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/interfect/cjdns-installer/issues/13#issuecomment-319577808>,
or mute the thread
