### ISSUE TITLE
Not peering locally

### ISSUE THREAD

**Issue by ghost** [interfect/cjdns-installer#17]
I have cjdns running fine on my OpenWrt router. I also installed it on my Linux machine and it automatically showed up on my router's active peers list and I can ping to and from just fine with either. On my Windows machine the story's a little different though.

I installed this and got an IPv6 address, but it does not show up in the peers list. I disabled the public peers option as I don't plan on connecting to Hyperboria at the moment. Is there anything I'm missing?

**Comment by interfect** [comment]
Unfortunately there is: the auto-peering relies on some OS-specific code
(since it's reading and writing raw Ethernet frames, instead of doing
something normal like TCP or UDP), and the code to do it on Windows hasn't
been written yet.

Windows machines need to be peered manually, by editing the config file. Is
that something you can do yourself, or would you like some instructions?

**Comment by ghost** [comment]
@interfect Sorry, I'd love some instructions if that's okay with you.

**Comment by interfect** [comment]
On the Windows machine, you have to do this process: https://github.com/interfect/cjdns-installer/blob/master/Users%20Guide.md#add-more-peers

But you need the "peering credentials" from the machine you want to connect to. In the `cjdroute.conf` file of the machine you want to connect to (`/etc/cjdroute.conf` on the Linux machine), there should be example credentials for that particular machine, as a comment. Something like:

```
        "your.external.ip.goes.here:45242": {
            "login": "default-login",
            "password":"98c8bb4lszs48qf5pc6lhgqtb39gtys",
            "publicKey":"2lszwm8d15ms41by33xy9wcbdqvd4cw2tyr769d98t20xmyuzxz0.k",
            "peerName":"your-name-goes-here"
        },
```

Copy-paste those from the machine you are trying to connect to, replace `your.external.ip.goes.here` with the *LAN* IP of the machine you want to connect to (which has to be fixed for this to work), and replace `your-name-goes-here` with a name to identify the machine you are connecting to (something like "Linux").

Then add those credentials where you see `// Ask somebody who is already connected.` in the config file of the Windows machine that you are making connect to the other machine, following the Users Guide instructions.

Peering the Windows machine with the router is a bit tougher, because I'm not sure where to find the credentials in the router UI. But if you can find similar information there, you should be able to use the same process.

**Comment by ghost** [comment]
Thank you, I finally managed to get it working
