### ISSUE TITLE
not work with Yggdrasil

### ISSUE THREAD

**Issue by ghost** [interfect/cjdns-installer#21]
https://yggdrasil-network.github.io/platform-windows.html

**Comment by interfect** [comment]
Yeah, this installer doesn't install Yggdrasil. You're welcome to fork it, but I don't anticipate maintaining a fork for it in the near future, because I don't actually use Yggrdasil.

I'm going to close this as won't-fix, but it's definitely a good idea for someone to do. The install process you linked seems rather involved.
